### ISSUE TITLE
Screen shots are cut off

### ISSUE THREAD

**Issue by ashleemikeyoung** [chadondata/659Files#1]
One of the problems with the exercises here is that in several of the screen shots, where we are given code to type, the right hand margin is cutting off the text. So if someone actually types what's written, it's going to result in an error. E.g., on page 10, line 84, we're told to select "dbo.vc_VidCastCount(vc_UserID) as VidCastC". It should read "dbo.vc_VidCastCount(vc_UserID) as VidCastCount".  We can see another example of this on page 11. On line 94, procedure is going to use two variables. One is @userName, which is a varchar(20). The other variable is @newEmail, which we're told is a "var". It's not a var. It's a varchar and we need to specify how many characters we are reserving for it.

**Comment by chadondata** [comment]
Fixed! Thanks much!
